/** @type {!Object} */
var Accessibility = {};
/** @type {!Object} */
var Animation = {};
/** @type {!Object} */
var Audits = {};
/** @type {!Object} */
var Audits2 = {};
/** @type {!Object} */
var Bindings = {};
/** @type {!Object} */
var Cm = {};
/** @type {!Object} */
var CmHeadless = {};
/** @type {!Object} */
var CmModes = {};
/** @type {!Object} */
var ColorPicker = {};
/** @type {!Object} */
var Common = {};
/** @type {!Object} */
var Components = {};
/** @type {!Object} */
var CookieTable = {};
/** @type {!Object} */
var Coverage = {};
/** @type {!Object} */
var DataGrid = {};
/** @type {!Object} */
var Devices = {};
/** @type {!Object} */
var Diff = {};
/** @type {!Object} */
var Dirac = {};
/** @type {!Object} */
var DiracLazy = {};
/** @type {!Object} */
var DomExtension = {};
/** @type {!Object} */
var Elements = {};
/** @type {!Object} */
var EmulatedDevices = {};
/** @type {!Object} */
var Emulation = {};
/** @type {!Object} */
var EventListeners = {};
/** @type {!Object} */
var Extensions = {};
/** @type {!Object} */
var FormatterWorker = {};
/** @type {!Object} */
var HeapSnapshotModel = {};
/** @type {!Object} */
var HeapSnapshotWorker = {};
/** @type {!Object} */
var Help = {};
/** @type {!Object} */
var Host = {};
/** @type {!Object} */
var InlineEditor = {};
/** @type {!Object} */
var LayerViewer = {};
/** @type {!Object} */
var Layers = {};
/** @type {!Object} */
var Main = {};
/** @type {!Object} */
var Network = {};
/** @type {!Object} */
var NetworkConditions = {};
/** @type {!Object} */
var NetworkGroupLookup = {};
/** @type {!Object} */
var ObjectUI = {};
/** @type {!Object} */
var PerfUI = {};
/** @type {!Object} */
var Persistence = {};
/** @type {!Object} */
var Platform = {};
/** @type {!Object} */
var ProductRegistry = {};
/** @type {!Object} */
var Profiler = {};
/** @type {!Object} */
var Protocol = {};
/** @type {!Object} */
var QuickOpen = {};
/** @type {!Object} */
var Resources = {};
/** @type {!Object} */
var SDK = {};
/** @type {!Object} */
var Sass = {};
/** @type {!Object} */
var Screencast = {};
/** @type {!Object} */
var Security = {};
/** @type {!Object} */
var Services = {};
/** @type {!Object} */
var Settings = {};
/** @type {!Object} */
var Shell = {};
/** @type {!Object} */
var Snippets = {};
/** @type {!Object} */
var SourceFrame = {};
/** @type {!Object} */
var Sources = {};
/** @type {!Object} */
var TestRunner = {};
/** @type {!Object} */
var TextEditor = {};
/** @type {!Object} */
var Timeline = {};
/** @type {!Object} */
var TimelineModel = {};
/** @type {!Object} */
var ToolboxBootstrap = {};
/** @type {!Object} */
var UI = {};
/** @type {!Object} */
var UtilitySharedWorker = {};
/** @type {!Object} */
var WorkerService = {};
/** @type {!Object} */
var Workspace = {};
