WebInspector.BakedSupportedCSSPropertiesChromeTag='55.0.2882.4';
WebInspector.BakedSupportedCSSPropertiesChromeRev='1cf2282189036144048ff9233d31f2d2fc55eadf';
WebInspector.BakedSupportedCSSProperties=''
+ '[{"name": "color", "inherited": true},\n'
+ ' {"name": "direction", "inherited": true},\n'
+ ' {"name": "font-family", "inherited": true},\n'
+ ' {"name": "font-kerning", "inherited": true},\n'
+ ' {"name": "font-size", "inherited": true},\n'
+ ' {"name": "font-size-adjust", "inherited": true},\n'
+ ' {"name": "font-stretch", "inherited": true},\n'
+ ' {"name": "font-style", "inherited": true},\n'
+ ' {"name": "font-variant-ligatures", "inherited": true},\n'
+ ' {"name": "font-variant-caps", "inherited": true},\n'
+ ' {"name": "font-variant-numeric", "inherited": true},\n'
+ ' {"name": "font-weight", "inherited": true},\n'
+ ' {"name": "font-feature-settings", "inherited": true},\n'
+ ' {"name": "-webkit-font-smoothing", "inherited": true},\n'
+ ' {"name": "-webkit-locale", "inherited": true},\n'
+ ' {"name": "text-orientation", "inherited": true},\n'
+ ' {"name": "-webkit-text-orientation", "inherited": true},\n'
+ ' {"name": "writing-mode", "inherited": true},\n'
+ ' {"name": "-webkit-writing-mode", "inherited": true},\n'
+ ' {"name": "text-rendering", "inherited": true},\n'
+ ' {"name": "zoom"},\n'
+ ' {"name": "align-content"},\n'
+ ' {"name": "align-items"},\n'
+ ' {"name": "alignment-baseline"},\n'
+ ' {"name": "align-self"},\n'
+ ' {"name": "animation-delay"},\n'
+ ' {"name": "animation-direction"},\n'
+ ' {"name": "animation-duration"},\n'
+ ' {"name": "animation-fill-mode"},\n'
+ ' {"name": "animation-iteration-count"},\n'
+ ' {"name": "animation-name"},\n'
+ ' {"name": "animation-play-state"},\n'
+ ' {"name": "animation-timing-function"},\n'
+ ' {"name": "backdrop-filter"},\n'
+ ' {"name": "backface-visibility"},\n'
+ ' {"name": "background-attachment"},\n'
+ ' {"name": "background-blend-mode"},\n'
+ ' {"name": "background-clip"},\n'
+ ' {"name": "background-color"},\n'
+ ' {"name": "background-image"},\n'
+ ' {"name": "background-origin"},\n'
+ ' {"name": "background-position-x"},\n'
+ ' {"name": "background-position-y"},\n'
+ ' {"name": "background-repeat-x"},\n'
+ ' {"name": "background-repeat-y"},\n'
+ ' {"name": "background-size"},\n'
+ ' {"name": "baseline-shift"},\n'
+ ' {"name": "border-bottom-color"},\n'
+ ' {"name": "border-bottom-left-radius"},\n'
+ ' {"name": "border-bottom-right-radius"},\n'
+ ' {"name": "border-bottom-style"},\n'
+ ' {"name": "border-bottom-width"},\n'
+ ' {"name": "border-collapse", "inherited": true},\n'
+ ' {"name": "border-image-outset"},\n'
+ ' {"name": "border-image-repeat"},\n'
+ ' {"name": "border-image-slice"},\n'
+ ' {"name": "border-image-source"},\n'
+ ' {"name": "border-image-width"},\n'
+ ' {"name": "border-left-color"},\n'
+ ' {"name": "border-left-style"},\n'
+ ' {"name": "border-left-width"},\n'
+ ' {"name": "border-right-color"},\n'
+ ' {"name": "border-right-style"},\n'
+ ' {"name": "border-right-width"},\n'
+ ' {"name": "border-top-color"},\n'
+ ' {"name": "border-top-left-radius"},\n'
+ ' {"name": "border-top-right-radius"},\n'
+ ' {"name": "border-top-style"},\n'
+ ' {"name": "border-top-width"},\n'
+ ' {"name": "bottom"},\n'
+ ' {"name": "box-shadow"},\n'
+ ' {"name": "box-sizing"},\n'
+ ' {"name": "break-after"},\n'
+ ' {"name": "break-before"},\n'
+ ' {"name": "break-inside"},\n'
+ ' {"name": "buffered-rendering"},\n'
+ ' {"name": "caption-side", "inherited": true},\n'
+ ' {"name": "clear"},\n'
+ ' {"name": "clip"},\n'
+ ' {"name": "clip-path"},\n'
+ ' {"name": "clip-rule", "inherited": true},\n'
+ ' {"name": "color-interpolation", "inherited": true},\n'
+ ' {"name": "color-interpolation-filters", "inherited": true},\n'
+ ' {"name": "color-rendering", "inherited": true},\n'
+ ' {"name": "column-fill"},\n'
+ ' {"name": "contain"},\n'
+ ' {"name": "content"},\n'
+ ' {"name": "counter-increment"},\n'
+ ' {"name": "counter-reset"},\n'
+ ' {"name": "cursor", "inherited": true},\n'
+ ' {"name": "cx"},\n'
+ ' {"name": "cy"},\n'
+ ' {"name": "d"},\n'
+ ' {"name": "display"},\n'
+ ' {"name": "dominant-baseline", "inherited": true},\n'
+ ' {"name": "empty-cells", "inherited": true},\n'
+ ' {"name": "fill", "inherited": true},\n'
+ ' {"name": "fill-opacity", "inherited": true},\n'
+ ' {"name": "fill-rule", "inherited": true},\n'
+ ' {"name": "filter"},\n'
+ ' {"name": "flex-basis"},\n'
+ ' {"name": "flex-direction"},\n'
+ ' {"name": "flex-grow"},\n'
+ ' {"name": "flex-shrink"},\n'
+ ' {"name": "flex-wrap"},\n'
+ ' {"name": "float"},\n'
+ ' {"name": "flood-color"},\n'
+ ' {"name": "flood-opacity"},\n'
+ ' {"name": "grid-auto-columns"},\n'
+ ' {"name": "grid-auto-flow"},\n'
+ ' {"name": "grid-auto-rows"},\n'
+ ' {"name": "grid-column-end"},\n'
+ ' {"name": "grid-column-gap"},\n'
+ ' {"name": "grid-column-start"},\n'
+ ' {"name": "grid-row-end"},\n'
+ ' {"name": "grid-row-gap"},\n'
+ ' {"name": "grid-row-start"},\n'
+ ' {"name": "grid-template-areas"},\n'
+ ' {"name": "grid-template-columns"},\n'
+ ' {"name": "grid-template-rows"},\n'
+ ' {"name": "height"},\n'
+ ' {"name": "hyphens", "inherited": true},\n'
+ ' {"name": "image-rendering", "inherited": true},\n'
+ ' {"name": "image-orientation", "inherited": true},\n'
+ ' {"name": "isolation"},\n'
+ ' {"name": "justify-content"},\n'
+ ' {"name": "justify-items"},\n'
+ ' {"name": "justify-self"},\n'
+ ' {"name": "left"},\n'
+ ' {"name": "letter-spacing", "inherited": true},\n'
+ ' {"name": "lighting-color"},\n'
+ ' {"name": "line-height", "inherited": true},\n'
+ ' {"name": "list-style-image", "inherited": true},\n'
+ ' {"name": "list-style-position", "inherited": true},\n'
+ ' {"name": "list-style-type", "inherited": true},\n'
+ ' {"name": "margin-bottom"},\n'
+ ' {"name": "margin-left"},\n'
+ ' {"name": "margin-right"},\n'
+ ' {"name": "margin-top"},\n'
+ ' {"name": "marker-end", "inherited": true},\n'
+ ' {"name": "marker-mid", "inherited": true},\n'
+ ' {"name": "marker-start", "inherited": true},\n'
+ ' {"name": "mask"},\n'
+ ' {"name": "mask-source-type"},\n'
+ ' {"name": "mask-type"},\n'
+ ' {"name": "max-height"},\n'
+ ' {"name": "max-width"},\n'
+ ' {"name": "min-height"},\n'
+ ' {"name": "min-width"},\n'
+ ' {"name": "mix-blend-mode"},\n'
+ ' {"name": "object-fit"},\n'
+ ' {"name": "object-position"},\n'
+ ' {"name": "offset-anchor"},\n'
+ ' {"name": "offset-distance"},\n'
+ ' {"name": "offset-path"},\n'
+ ' {"name": "offset-position"},\n'
+ ' {"name": "offset-rotation"},\n'
+ ' {"name": "opacity"},\n'
+ ' {"name": "order"},\n'
+ ' {"name": "orphans", "inherited": true},\n'
+ ' {"name": "outline-color"},\n'
+ ' {"name": "outline-offset"},\n'
+ ' {"name": "outline-style"},\n'
+ ' {"name": "outline-width"},\n'
+ ' {"name": "overflow-anchor"},\n'
+ ' {"name": "overflow-wrap", "inherited": true},\n'
+ ' {"name": "overflow-x"},\n'
+ ' {"name": "overflow-y"},\n'
+ ' {"name": "padding-bottom"},\n'
+ ' {"name": "padding-left"},\n'
+ ' {"name": "padding-right"},\n'
+ ' {"name": "padding-top"},\n'
+ ' {"name": "paint-order", "inherited": true},\n'
+ ' {"name": "perspective"},\n'
+ ' {"name": "perspective-origin"},\n'
+ ' {"name": "pointer-events", "inherited": true},\n'
+ ' {"name": "position"},\n'
+ ' {"name": "quotes", "inherited": true},\n'
+ ' {"name": "resize"},\n'
+ ' {"name": "right"},\n'
+ ' {"name": "r"},\n'
+ ' {"name": "rx"},\n'
+ ' {"name": "ry"},\n'
+ ' {"name": "scroll-behavior"},\n'
+ ' {"name": "scroll-snap-type"},\n'
+ ' {"name": "scroll-snap-points-x"},\n'
+ ' {"name": "scroll-snap-points-y"},\n'
+ ' {"name": "scroll-snap-destination"},\n'
+ ' {"name": "scroll-snap-coordinate"},\n'
+ ' {"name": "shape-image-threshold"},\n'
+ ' {"name": "shape-margin"},\n'
+ ' {"name": "shape-outside"},\n'
+ ' {"name": "shape-rendering", "inherited": true},\n'
+ ' {"name": "size"},\n'
+ ' {"name": "snap-height", "inherited": true},\n'
+ ' {"name": "speak", "inherited": true},\n'
+ ' {"name": "stop-color"},\n'
+ ' {"name": "stop-opacity"},\n'
+ ' {"name": "stroke", "inherited": true},\n'
+ ' {"name": "stroke-dasharray", "inherited": true},\n'
+ ' {"name": "stroke-dashoffset", "inherited": true},\n'
+ ' {"name": "stroke-linecap", "inherited": true},\n'
+ ' {"name": "stroke-linejoin", "inherited": true},\n'
+ ' {"name": "stroke-miterlimit", "inherited": true},\n'
+ ' {"name": "stroke-opacity", "inherited": true},\n'
+ ' {"name": "stroke-width", "inherited": true},\n'
+ ' {"name": "table-layout"},\n'
+ ' {"name": "tab-size", "inherited": true},\n'
+ ' {"name": "text-align", "inherited": true},\n'
+ ' {"name": "text-align-last", "inherited": true},\n'
+ ' {"name": "text-anchor", "inherited": true},\n'
+ ' {"name": "text-combine-upright", "inherited": true},\n'
+ ' {"longhands": ["text-decoration-line", "text-decoration-style", "text-decoration-color"], "name": "text-decoration"},\n'
+ ' {"name": "text-decoration-color"},\n'
+ ' {"name": "text-decoration-line"},\n'
+ ' {"name": "text-decoration-style"},\n'
+ ' {"name": "text-indent", "inherited": true},\n'
+ ' {"name": "text-justify", "inherited": true},\n'
+ ' {"name": "text-overflow"},\n'
+ ' {"name": "text-shadow", "inherited": true},\n'
+ ' {"name": "text-size-adjust", "inherited": true},\n'
+ ' {"name": "text-transform", "inherited": true},\n'
+ ' {"name": "text-underline-position", "inherited": true},\n'
+ ' {"name": "top"},\n'
+ ' {"name": "touch-action"},\n'
+ ' {"name": "transform"},\n'
+ ' {"name": "transform-origin"},\n'
+ ' {"name": "transform-style"},\n'
+ ' {"name": "translate"},\n'
+ ' {"name": "rotate"},\n'
+ ' {"name": "scale"},\n'
+ ' {"name": "transition-delay"},\n'
+ ' {"name": "transition-duration"},\n'
+ ' {"name": "transition-property"},\n'
+ ' {"name": "transition-timing-function"},\n'
+ ' {"name": "unicode-bidi"},\n'
+ ' {"name": "vector-effect"},\n'
+ ' {"name": "vertical-align"},\n'
+ ' {"name": "visibility", "inherited": true},\n'
+ ' {"name": "x"},\n'
+ ' {"name": "y"},\n'
+ ' {"name": "-webkit-appearance"},\n'
+ ' {"name": "-webkit-app-region"},\n'
+ ' {"name": "-webkit-background-clip"},\n'
+ ' {"name": "-webkit-background-origin"},\n'
+ ' {"name": "-webkit-border-horizontal-spacing", "inherited": true},\n'
+ ' {"name": "-webkit-border-image"},\n'
+ ' {"name": "-webkit-border-vertical-spacing", "inherited": true},\n'
+ ' {"name": "-webkit-box-align"},\n'
+ ' {"name": "-webkit-box-decoration-break"},\n'
+ ' {"name": "-webkit-box-direction", "inherited": true},\n'
+ ' {"name": "-webkit-box-flex"},\n'
+ ' {"name": "-webkit-box-flex-group"},\n'
+ ' {"name": "-webkit-box-lines"},\n'
+ ' {"name": "-webkit-box-ordinal-group"},\n'
+ ' {"name": "-webkit-box-orient"},\n'
+ ' {"name": "-webkit-box-pack"},\n'
+ ' {"name": "-webkit-box-reflect"},\n'
+ ' {"name": "column-count"},\n'
+ ' {"name": "column-gap"},\n'
+ ' {"name": "column-rule-color"},\n'
+ ' {"name": "column-rule-style"},\n'
+ ' {"name": "column-rule-width"},\n'
+ ' {"name": "column-span"},\n'
+ ' {"name": "column-width"},\n'
+ ' {"name": "-webkit-highlight", "inherited": true},\n'
+ ' {"name": "-webkit-hyphenate-character", "inherited": true},\n'
+ ' {"name": "-webkit-line-break", "inherited": true},\n'
+ ' {"name": "-webkit-line-clamp"},\n'
+ ' {"name": "-webkit-margin-after-collapse"},\n'
+ ' {"name": "-webkit-margin-before-collapse"},\n'
+ ' {"name": "-webkit-margin-bottom-collapse"},\n'
+ ' {"name": "-webkit-margin-top-collapse"},\n'
+ ' {"name": "-webkit-mask-box-image-outset"},\n'
+ ' {"name": "-webkit-mask-box-image-repeat"},\n'
+ ' {"name": "-webkit-mask-box-image-slice"},\n'
+ ' {"name": "-webkit-mask-box-image-source"},\n'
+ ' {"name": "-webkit-mask-box-image-width"},\n'
+ ' {"name": "-webkit-mask-clip"},\n'
+ ' {"name": "-webkit-mask-composite"},\n'
+ ' {"name": "-webkit-mask-image"},\n'
+ ' {"name": "-webkit-mask-origin"},\n'
+ ' {"name": "-webkit-mask-position-x"},\n'
+ ' {"name": "-webkit-mask-position-y"},\n'
+ ' {"name": "-webkit-mask-repeat-x"},\n'
+ ' {"name": "-webkit-mask-repeat-y"},\n'
+ ' {"name": "-webkit-mask-size"},\n'
+ ' {"name": "-webkit-perspective-origin-x"},\n'
+ ' {"name": "-webkit-perspective-origin-y"},\n'
+ ' {"name": "-webkit-print-color-adjust", "inherited": true},\n'
+ ' {"name": "-webkit-rtl-ordering", "inherited": true},\n'
+ ' {"name": "-webkit-ruby-position", "inherited": true},\n'
+ ' {"name": "-webkit-tap-highlight-color", "inherited": true},\n'
+ ' {"name": "-webkit-text-combine", "inherited": true},\n'
+ ' {"name": "-webkit-text-emphasis-color", "inherited": true},\n'
+ ' {"name": "-webkit-text-emphasis-position", "inherited": true},\n'
+ ' {"name": "-webkit-text-emphasis-style", "inherited": true},\n'
+ ' {"name": "-webkit-text-fill-color", "inherited": true},\n'
+ ' {"name": "-webkit-text-security", "inherited": true},\n'
+ ' {"name": "-webkit-text-stroke-color", "inherited": true},\n'
+ ' {"name": "-webkit-text-stroke-width", "inherited": true},\n'
+ ' {"name": "-webkit-transform-origin-x"},\n'
+ ' {"name": "-webkit-transform-origin-y"},\n'
+ ' {"name": "-webkit-transform-origin-z"},\n'
+ ' {"name": "-webkit-user-drag"},\n'
+ ' {"name": "-webkit-user-modify", "inherited": true},\n'
+ ' {"name": "user-select", "inherited": true},\n'
+ ' {"name": "white-space", "inherited": true},\n'
+ ' {"name": "widows", "inherited": true},\n'
+ ' {"name": "width"},\n'
+ ' {"name": "will-change"},\n'
+ ' {"name": "word-break", "inherited": true},\n'
+ ' {"name": "word-spacing", "inherited": true},\n'
+ ' {"name": "word-wrap", "inherited": true},\n'
+ ' {"name": "z-index"},\n'
+ ' {"name": "-webkit-border-end-color"},\n'
+ ' {"name": "-webkit-border-end-style"},\n'
+ ' {"name": "-webkit-border-end-width"},\n'
+ ' {"name": "-webkit-border-start-color"},\n'
+ ' {"name": "-webkit-border-start-style"},\n'
+ ' {"name": "-webkit-border-start-width"},\n'
+ ' {"name": "-webkit-border-before-color"},\n'
+ ' {"name": "-webkit-border-before-style"},\n'
+ ' {"name": "-webkit-border-before-width"},\n'
+ ' {"name": "-webkit-border-after-color"},\n'
+ ' {"name": "-webkit-border-after-style"},\n'
+ ' {"name": "-webkit-border-after-width"},\n'
+ ' {"name": "-webkit-margin-end"},\n'
+ ' {"name": "-webkit-margin-start"},\n'
+ ' {"name": "-webkit-margin-before"},\n'
+ ' {"name": "-webkit-margin-after"},\n'
+ ' {"name": "-webkit-padding-end"},\n'
+ ' {"name": "-webkit-padding-start"},\n'
+ ' {"name": "-webkit-padding-before"},\n'
+ ' {"name": "-webkit-padding-after"},\n'
+ ' {"name": "-webkit-logical-width"},\n'
+ ' {"name": "-webkit-logical-height"},\n'
+ ' {"name": "-webkit-min-logical-width"},\n'
+ ' {"name": "-webkit-min-logical-height"},\n'
+ ' {"name": "-webkit-max-logical-width"},\n'
+ ' {"name": "-webkit-max-logical-height"},\n'
+ ' {"name": "all"},\n'
+ ' {"name": "page"},\n'
+ ' {"name": "-webkit-font-size-delta"},\n'
+ ' {"name": "-webkit-text-decorations-in-effect", "inherited": true},\n'
+ ' {"name": "font-display"},\n'
+ ' {"name": "max-zoom"},\n'
+ ' {"name": "min-zoom"},\n'
+ ' {"name": "orientation"},\n'
+ ' {"name": "src"},\n'
+ ' {"name": "unicode-range"},\n'
+ ' {"name": "user-zoom"},\n'
+ ' {"longhands": ["animation-name", "animation-duration", "animation-timing-function", "animation-delay", "animation-iteration-count", "animation-direction", "animation-fill-mode", "animation-play-state"], "name": "animation"},\n'
+ ' {"longhands": ["background-image", "background-position-x", "background-position-y", "background-size", "background-repeat-x", "background-repeat-y", "background-attachment", "background-origin", "background-clip", "background-color"], "name": "background"},\n'
+ ' {"longhands": ["background-position-x", "background-position-y"], "name": "background-position"},\n'
+ ' {"longhands": ["background-repeat-x", "background-repeat-y"], "name": "background-repeat"},\n'
+ ' {"longhands": ["border-top-color", "border-top-style", "border-top-width", "border-right-color", "border-right-style", "border-right-width", "border-bottom-color", "border-bottom-style", "border-bottom-width", "border-left-color", "border-left-style", "border-left-width", "border-image-source", "border-image-slice", "border-image-width", "border-image-outset", "border-image-repeat"], "name": "border"},\n'
+ ' {"longhands": ["border-bottom-width", "border-bottom-style", "border-bottom-color"], "name": "border-bottom"},\n'
+ ' {"longhands": ["border-top-color", "border-right-color", "border-bottom-color", "border-left-color"], "name": "border-color"},\n'
+ ' {"longhands": ["border-image-source", "border-image-slice", "border-image-width", "border-image-outset", "border-image-repeat"], "name": "border-image"},\n'
+ ' {"longhands": ["border-left-width", "border-left-style", "border-left-color"], "name": "border-left"},\n'
+ ' {"longhands": ["border-top-left-radius", "border-top-right-radius", "border-bottom-right-radius", "border-bottom-left-radius"], "name": "border-radius"},\n'
+ ' {"longhands": ["border-right-width", "border-right-style", "border-right-color"], "name": "border-right"},\n'
+ ' {"longhands": ["-webkit-border-horizontal-spacing", "-webkit-border-vertical-spacing"], "name": "border-spacing"},\n'
+ ' {"longhands": ["border-top-style", "border-right-style", "border-bottom-style", "border-left-style"], "name": "border-style"},\n'
+ ' {"longhands": ["border-top-width", "border-top-style", "border-top-color"], "name": "border-top"},\n'
+ ' {"longhands": ["border-top-width", "border-right-width", "border-bottom-width", "border-left-width"], "name": "border-width"},\n'
+ ' {"longhands": ["flex-grow", "flex-shrink", "flex-basis"], "name": "flex"},\n'
+ ' {"longhands": ["flex-direction", "flex-wrap"], "name": "flex-flow"},\n'
+ ' {"longhands": ["font-style", "font-variant-ligatures", "font-variant-caps", "font-variant-numeric", "font-weight", "font-stretch", "font-size", "line-height", "font-family"], "name": "font"},\n'
+ ' {"longhands": ["font-variant-ligatures", "font-variant-caps", "font-variant-numeric"], "name": "font-variant"},\n'
+ ' {"longhands": ["grid-template-rows", "grid-template-columns", "grid-template-areas", "grid-auto-flow", "grid-auto-rows", "grid-auto-columns", "grid-column-gap", "grid-row-gap"], "name": "grid"},\n'
+ ' {"longhands": ["grid-row-start", "grid-column-start", "grid-row-end", "grid-column-end"], "name": "grid-area"},\n'
+ ' {"longhands": ["grid-column-start", "grid-column-end"], "name": "grid-column"},\n'
+ ' {"longhands": ["grid-row-gap", "grid-column-gap"], "name": "grid-gap"},\n'
+ ' {"longhands": ["grid-row-start", "grid-row-end"], "name": "grid-row"},\n'
+ ' {"longhands": ["grid-template-rows", "grid-template-columns", "grid-template-areas"], "name": "grid-template"},\n'
+ ' {"longhands": ["list-style-type", "list-style-position", "list-style-image"], "name": "list-style"},\n'
+ ' {"longhands": ["margin-top", "margin-right", "margin-bottom", "margin-left"], "name": "margin"},\n'
+ ' {"longhands": ["marker-start", "marker-mid", "marker-end"], "name": "marker"},\n'
+ ' {"longhands": ["offset-path", "offset-distance", "offset-rotation"], "name": "motion"},\n'
+ ' {"longhands": ["offset-path", "offset-distance", "offset-rotation"], "name": "offset"},\n'
+ ' {"longhands": ["outline-color", "outline-style", "outline-width"], "name": "outline"},\n'
+ ' {"longhands": ["overflow-x", "overflow-y"], "name": "overflow"},\n'
+ ' {"longhands": ["padding-top", "padding-right", "padding-bottom", "padding-left"], "name": "padding"},\n'
+ ' {"longhands": ["break-after"], "name": "page-break-after"},\n'
+ ' {"longhands": ["break-before"], "name": "page-break-before"},\n'
+ ' {"longhands": ["break-inside"], "name": "page-break-inside"},\n'
+ ' {"longhands": ["transition-property", "transition-duration", "transition-timing-function", "transition-delay"], "name": "transition"},\n'
+ ' {"longhands": ["-webkit-border-after-width", "-webkit-border-after-style", "-webkit-border-after-color"], "name": "-webkit-border-after"},\n'
+ ' {"longhands": ["-webkit-border-before-width", "-webkit-border-before-style", "-webkit-border-before-color"], "name": "-webkit-border-before"},\n'
+ ' {"longhands": ["-webkit-border-end-width", "-webkit-border-end-style", "-webkit-border-end-color"], "name": "-webkit-border-end"},\n'
+ ' {"longhands": ["-webkit-border-start-width", "-webkit-border-start-style", "-webkit-border-start-color"], "name": "-webkit-border-start"},\n'
+ ' {"longhands": ["break-after"], "name": "-webkit-column-break-after"},\n'
+ ' {"longhands": ["break-before"], "name": "-webkit-column-break-before"},\n'
+ ' {"longhands": ["break-inside"], "name": "-webkit-column-break-inside"},\n'
+ ' {"longhands": ["column-rule-width", "column-rule-style", "column-rule-color"], "name": "column-rule"},\n'
+ ' {"longhands": ["column-width", "column-count"], "name": "columns"},\n'
+ ' {"longhands": ["-webkit-margin-before-collapse", "-webkit-margin-after-collapse"], "name": "-webkit-margin-collapse"},\n'
+ ' {"longhands": ["-webkit-mask-image", "-webkit-mask-position-x", "-webkit-mask-position-y", "-webkit-mask-size", "-webkit-mask-repeat-x", "-webkit-mask-repeat-y", "-webkit-mask-origin", "-webkit-mask-clip"], "name": "-webkit-mask"},\n'
+ ' {"longhands": ["-webkit-mask-box-image-source", "-webkit-mask-box-image-slice", "-webkit-mask-box-image-width", "-webkit-mask-box-image-outset", "-webkit-mask-box-image-repeat"], "name": "-webkit-mask-box-image"},\n'
+ ' {"longhands": ["-webkit-mask-position-x", "-webkit-mask-position-y"], "name": "-webkit-mask-position"},\n'
+ ' {"longhands": ["-webkit-mask-repeat-x", "-webkit-mask-repeat-y"], "name": "-webkit-mask-repeat"},\n'
+ ' {"longhands": ["-webkit-text-emphasis-style", "-webkit-text-emphasis-color"], "name": "-webkit-text-emphasis"},\n'
+ ' {"longhands": ["-webkit-text-stroke-width", "-webkit-text-stroke-color"], "name": "-webkit-text-stroke"}]\n';