#!/usr/bin/env bash

# darwin's machine
if [ "$USER" = "darwin" ]; then

  export DIRAC_DEVTOOLS_WINDOW_TOP="0"
  export DIRAC_DEVTOOLS_WINDOW_LEFT="-2560"
  export DIRAC_DEVTOOLS_WINDOW_WIDTH="1280"
  export DIRAC_DEVTOOLS_WINDOW_HEIGHT="1115"

  export DIRAC_RUNNER_WINDOW_TOP="0"
  export DIRAC_RUNNER_WINDOW_LEFT="-1280"
  export DIRAC_RUNNER_WINDOW_WIDTH="1280"
  export DIRAC_RUNNER_WINDOW_HEIGHT="815"

  export DIRAC_SCENARIO_WINDOW_TOP="815"
  export DIRAC_SCENARIO_WINDOW_LEFT="-1280"
  export DIRAC_SCENARIO_WINDOW_WIDTH="1280"
  export DIRAC_SCENARIO_WINDOW_HEIGHT="300"

fi
